addon-name: "Lib's - Remix Power Level"
addon-description: "power level tracking for Remix content"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/libs-remixpowerlevel"
  wago: "https://addons.wago.io/addons/vNAe8BNo"
  discord: "https://discord.gg/Qc9TRBv"
